title: Harald Steinlechner | Boosting applications
show_downloads: false
google_analytics: false
theme: jekyll-theme-cayman
tagline: High-Performance Solutions | Functional Programming Courses | Parallel Programming Courses | Courses in Austria | Remote Teaching | GPU Programming consulting | Funktionale Programmierung Wien | Funktionale Programmierung Österreich
description: Boosting applications.
twitter: HaraldSteinlec1